"""Initial 9 tables schema

Revision ID: b59055f42745
Revises: 
Create Date: 2026-09-16 23:30:15.345771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b59055f42745'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('ten_van_ban', sa.Text(), nullable=False),
    sa.Column('so_hieu', sa.String(length=100), nullable=True),
    sa.Column('loai_van_ban', sa.String(length=100), nullable=True),
    sa.Column('chu_de', sa.String(length=100), nullable=True),
    sa.Column('pham_vi_ap_dung', sa.String(length=100), nullable=True),
    sa.Column('nguon_du_lieu', sa.String(length=100), nullable=True),
    sa.Column('ngay_ban_hanh', sa.Date(), nullable=True),
    sa.Column('co_quan_ban_hanh', sa.String(length=200), nullable=True),
    sa.Column('file_goc_url', sa.String(length=500), nullable=True),
    sa.Column('trang_thai_hieu_luc', sa.String(length=50), nullable=False),
    sa.Column('trang_thai_xuat_ban', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_chu_de'), 'documents', ['chu_de'], unique=False)
    op.create_index(op.f('ix_documents_so_hieu'), 'documents', ['so_hieu'], unique=False)
    op.create_index(op.f('ix_documents_trang_thai_xuat_ban'), 'documents', ['trang_thai_xuat_ban'], unique=False)
    op.create_table('query_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cau_hoi', sa.Text(), nullable=False),
    sa.Column('cau_tra_loi', sa.Text(), nullable=False),
    sa.Column('danh_sach_citation', sa.JSON(), nullable=True),
    sa.Column('diem_faithfulness', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('loai_bao_cao', sa.String(length=100), nullable=False),
    sa.Column('chu_de_ap_dung', sa.String(length=100), nullable=True),
    sa.Column('danh_sach_de_muc', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_templates_chu_de_ap_dung'), 'report_templates', ['chu_de_ap_dung'], unique=False)
    op.create_index(op.f('ix_report_templates_loai_bao_cao'), 'report_templates', ['loai_bao_cao'], unique=False)
    op.create_table('document_chunks',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('document_id', sa.String(length=100), nullable=False),
    sa.Column('dieu_khoan', sa.String(length=200), nullable=True),
    sa.Column('noi_dung', sa.Text(), nullable=False),
    sa.Column('so_trang', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False)
    op.create_table('document_relations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id_a', sa.String(length=100), nullable=False),
    sa.Column('document_id_b', sa.String(length=100), nullable=False),
    sa.Column('loai_quan_he', sa.String(length=100), nullable=False),
    sa.Column('diem_tuong_dong', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['document_id_a'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['document_id_b'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_relations_document_id_a'), 'document_relations', ['document_id_a'], unique=False)
    op.create_index(op.f('ix_document_relations_document_id_b'), 'document_relations', ['document_id_b'], unique=False)
    op.create_index(op.f('ix_document_relations_loai_quan_he'), 'document_relations', ['loai_quan_he'], unique=False)
    op.create_table('summaries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.String(length=100), nullable=False),
    sa.Column('noi_dung_tom_tat', sa.Text(), nullable=False),
    sa.Column('phien_ban_model', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_summaries_document_id'), 'summaries', ['document_id'], unique=False)
    op.create_table('citations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('summary_id', sa.Integer(), nullable=True),
    sa.Column('chunk_id', sa.String(length=100), nullable=False),
    sa.Column('cau_tom_tat', sa.Text(), nullable=False),
    sa.Column('diem_faithfulness', sa.Float(), nullable=False),
    sa.Column('nhan_nli', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['document_chunks.id'], ),
    sa.ForeignKeyConstraint(['summary_id'], ['summaries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_citations_chunk_id'), 'citations', ['chunk_id'], unique=False)
    op.create_index(op.f('ix_citations_nhan_nli'), 'citations', ['nhan_nli'], unique=False)
    op.create_index(op.f('ix_citations_summary_id'), 'citations', ['summary_id'], unique=False)
    op.create_table('review_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('citation_id', sa.Integer(), nullable=True),
    sa.Column('document_id', sa.String(length=100), nullable=False),
    sa.Column('nhan_nli', sa.String(length=50), nullable=False),
    sa.Column('do_uu_tien', sa.String(length=50), nullable=False),
    sa.Column('trang_thai', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['citation_id'], ['citations.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_items_citation_id'), 'review_items', ['citation_id'], unique=False)
    op.create_index(op.f('ix_review_items_do_uu_tien'), 'review_items', ['do_uu_tien'], unique=False)
    op.create_index(op.f('ix_review_items_document_id'), 'review_items', ['document_id'], unique=False)
    op.create_index(op.f('ix_review_items_nhan_nli'), 'review_items', ['nhan_nli'], unique=False)
    op.create_index(op.f('ix_review_items_trang_thai'), 'review_items', ['trang_thai'], unique=False)
    op.create_table('review_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('review_item_id', sa.Integer(), nullable=False),
    sa.Column('cau_ai_sinh', sa.Text(), nullable=False),
    sa.Column('cau_sau_sua', sa.Text(), nullable=True),
    sa.Column('reviewer_id', sa.String(length=100), nullable=False),
    sa.Column('hanh_dong', sa.String(length=50), nullable=False),
    sa.Column('diem_nli_sau_sua', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['review_item_id'], ['review_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_logs_review_item_id'), 'review_logs', ['review_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_logs_review_item_id'), table_name='review_logs')
    op.drop_table('review_logs')
    op.drop_index(op.f('ix_review_items_trang_thai'), table_name='review_items')
    op.drop_index(op.f('ix_review_items_nhan_nli'), table_name='review_items')
    op.drop_index(op.f('ix_review_items_document_id'), table_name='review_items')
    op.drop_index(op.f('ix_review_items_do_uu_tien'), table_name='review_items')
    op.drop_index(op.f('ix_review_items_citation_id'), table_name='review_items')
    op.drop_table('review_items')
    op.drop_index(op.f('ix_citations_summary_id'), table_name='citations')
    op.drop_index(op.f('ix_citations_nhan_nli'), table_name='citations')
    op.drop_index(op.f('ix_citations_chunk_id'), table_name='citations')
    op.drop_table('citations')
    op.drop_index(op.f('ix_summaries_document_id'), table_name='summaries')
    op.drop_table('summaries')
    op.drop_index(op.f('ix_document_relations_loai_quan_he'), table_name='document_relations')
    op.drop_index(op.f('ix_document_relations_document_id_b'), table_name='document_relations')
    op.drop_index(op.f('ix_document_relations_document_id_a'), table_name='document_relations')
    op.drop_table('document_relations')
    op.drop_index(op.f('ix_document_chunks_document_id'), table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index(op.f('ix_report_templates_loai_bao_cao'), table_name='report_templates')
    op.drop_index(op.f('ix_report_templates_chu_de_ap_dung'), table_name='report_templates')
    op.drop_table('report_templates')
    op.drop_table('query_logs')
    op.drop_index(op.f('ix_documents_trang_thai_xuat_ban'), table_name='documents')
    op.drop_index(op.f('ix_documents_so_hieu'), table_name='documents')
    op.drop_index(op.f('ix_documents_chu_de'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
